name: Isar release

on:
  push:
    tags:
      - "*"

jobs:
  build_binaries:
    name: Build Binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: libisar_android_arm64.so
            script: build_android.sh
          - os: ubuntu-latest
            artifact_name: libisar_android_armv7.so
            script: build_android.sh armv7
          - os: ubuntu-latest
            artifact_name: libisar_android_x64.so
            script: build_android.sh x64
          - os: macos-latest
            artifact_name: isar_ios.xcframework.zip
            script: build_ios.sh
          - os: ubuntu-20.04
            artifact_name: libisar_linux_x64.so
            script: build_linux.sh x64
          - os: macos-latest
            artifact_name: libisar_macos.dylib
            script: build_macos.sh
          - os: windows-latest
            artifact_name: isar_windows_x64.dll
            script: build_windows.sh x64
          - os: ubuntu-latest
            artifact_name: isar.wasm
            script: build_wasm.sh
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Build
        uses: ./.github/actions/prepare-build
      - name: Set Isar Version
        run: echo "ISAR_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Build binary
        run: bash tool/${{ matrix.script }} ${{ matrix.parameters }}
      - name: Upload binaries to another repo
        if: ${{ success() && matrix.os == 'ubuntu-latest' }} # This ensures the upload step runs only once after all builds are successful.
        run: |
          git config --global user.email "vicente.russo@gmail.com"
          git config --global user.name "GitHub Actions"
          # Temporarily store binaries to avoid re-cloning for each matrix entry
          mkdir -p binaries
          mv ${{ matrix.artifact_name }} binaries/
        shell: bash
      - name: Push binaries to another repository
        env:
          TARGET_REPO: 'isar-private-testing/binaries'
          TARGET_BRANCH: 'main'
          COMMIT_MESSAGE: 'Deploy binaries'
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          # Clone the target repository
          git clone https://github.com/${TARGET_REPO} repo
          cd repo
          # Checkout to a specific branch or create it if it doesn't exist
          git checkout ${TARGET_BRANCH} || git checkout -b ${TARGET_BRANCH}
          # Copy binaries from the previous step
          cp ../binaries/* .
          # Add, commit, and push changes
          git add .
          git commit -m "Update binaries"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git ${TARGET_BRANCH}
